// File generated by FlutterFire CLI.
// This file contains platform-specific Firebase configuration options
// for initializing Firebase in your Flutter application.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Provides the default [FirebaseOptions] for each supported platform.
///
/// This class is used to select the correct Firebase configuration
/// depending on the platform the app is running on.
///
/// Usage:
///   await Firebase.initializeApp(
///     options: DefaultFirebaseOptions.currentPlatform,
///   );
class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] for the current platform.
  ///
  /// Throws [UnsupportedError] if the platform is not supported.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase configuration for Web platform.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ2Ul18E-ZiOSysUIJhLfPxJE4NeTrEhs',
    appId: '1:913247627945:web:321ba30b90a029439057b8',
    messagingSenderId: '913247627945',
    projectId: 'sololevelapp-5f31b',
    authDomain: 'sololevelapp-5f31b.firebaseapp.com',
    storageBucket: 'sololevelapp-5f31b.firebasestorage.app',
    measurementId: 'G-Q1GEBDHVHX',
  );

  /// Firebase configuration for Android platform.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5vQhf7Ny_5gLmQarJOhqp5vv_C9d3QwI',
    appId: '1:913247627945:android:9e1a8a40eafdc2b69057b8',
    messagingSenderId: '913247627945',
    projectId: 'sololevelapp-5f31b',
    storageBucket: 'sololevelapp-5f31b.firebasestorage.app',
  );

  /// Firebase configuration for iOS platform.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9649o_b9yvgNLNKltiDoBicINniwFa54',
    appId: '1:913247627945:ios:1df324ad2f679e6e9057b8',
    messagingSenderId: '913247627945',
    projectId: 'sololevelapp-5f31b',
    storageBucket: 'sololevelapp-5f31b.firebasestorage.app',
    iosBundleId: 'com.example.sololevelapp',
  );

  /// Firebase configuration for macOS platform.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9649o_b9yvgNLNKltiDoBicINniwFa54',
    appId: '1:913247627945:ios:1df324ad2f679e6e9057b8',
    messagingSenderId: '913247627945',
    projectId: 'sololevelapp-5f31b',
    storageBucket: 'sololevelapp-5f31b.firebasestorage.app',
    iosBundleId: 'com.example.sololevelapp',
  );

  /// Firebase configuration for Windows platform.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ2Ul18E-ZiOSysUIJhLfPxJE4NeTrEhs',
    appId: '1:913247627945:web:e5e86f023b0736b59057b8',
    messagingSenderId: '913247627945',
    projectId: 'sololevelapp-5f31b',
    authDomain: 'sololevelapp-5f31b.firebaseapp.com',
    storageBucket: 'sololevelapp-5f31b.firebasestorage.app',
    measurementId: 'G-7P1S06G4RZ',
  );
}
